var zoologyTableData = [
  {
    index: "1",
    descriptor: "氧平衡过程：动植物呼吸作用",
    unit: "/day",
    value: "3",
    index1: "11",
    descriptor1: "沉积过程：有机物沉降速率",
    unit1: "m/day",
    value1: "0.8",
  },
  {
    index: "2",
    descriptor: "氧平衡过程：光合作用最大氧速率",
    unit: "/day",
    value: "3.5",
    index1: "12",
    descriptor1: "沉积过程：临界流速",
    unit1: "m/s",
    value1: "1",
  },
  {
    index: "3",
    descriptor: "氧平衡过程：动植物呼吸作用",
    unit: "-",
    value: "1",
    index1: "13",
    descriptor1: "氧平衡常数：BOD氧化速率",
    unit1: "gNH4/gBOD",
    value1: "0.29",
  },
  {
    index: "4",
    descriptor: "一阶降解系数（20℃）",
    unit: "/day",
    value: "0.4",
    index1: "14",
    descriptor1: "氧平衡常数：植物吸收氨氮常数",
    unit1: "无量纲",
    value1: "0.066",
  },
  {
    index: "5",
    descriptor: "溶解氧的半饱和浓度",
    unit: "mg/L",
    value: "2",
    index1: "15",
    descriptor1: "氮平衡常数：细菌吸收氨氮常数",
    unit1: "无量纲",
    value1: "0.109",
  },
  {
    index: "6",
    descriptor: "氧平衡过程：反应常数1",
    unit: "/day",
    value: "1",
    index1: "16",
    descriptor1: "氮化：一二阶反应常数",
    unit1: "无量纲",
    value1: "1",
  },
  {
    index: "7",
    descriptor: "氧平衡过程：反应常数2",
    unit: "/day",
    value: "1",
    index1: "17",
    descriptor1: "氮化：氨氮讲解系数（20度）",
    unit1: "m/s",
    value1: "1.54",
  },
  {
    index: "8",
    descriptor: "氧平衡过程：反应常数3",
    unit: "/day",
    value: "1",
    index1: "18",
    descriptor1: "脱氮：氮化需氧量",
    unit1: "gO2/gHN4",
    value1: "4.47",
  },
  {
    index: "9",
    descriptor: "沉积过程：底泥耗氧量",
    unit: "g/㎡/day",
    value: "0.5",
    index1: "19",
    descriptor1: "脱氮：半饱和常数",
    unit1: "mg/L",
    value1: "0.05",
  },
  {
    index: "10",
    descriptor: "沉积过程：有机物在悬浮",
    unit: "g/㎡/day",
    value: "0.5",
    index1: "20",
    descriptor1: "脱氮：氮气释放常数",
    unit1: "/day",
    value1: "1",
  },

]

export default zoologyTableData
